name: reuseable-deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      image_tag:
        type: string
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - run: echo "Deploying image ${{inputs.image_tag}} to ${{inputs.environment}} "
      - run: echo "Running smoke test on ${{inputs.environment}}"